
# Add to compile flags: turn on most warnings and make all warnings into errors (safely)
CFLAGS += -Wall -Werror
# LDFLAGS - mostly required if a dynamic linking is used
LDFLAGS +=

TARGET = htbl		# Name of main binary output
HDRS = htbl.h		# global headers
SRCS = htbl.c text.c			# sources of target
OBJS = $(patsubst %.c,%.o,$(SRCS))	# build objs list from the src list

# The first target is also the default target, i.e. if the command is just "make".
# The general from for a target is>
# target_name : prerequisits list
# <tab> shell command 1
# <tab> shell command 2
# ...
${TARGET}: ${OBJS}
	${CC} ${LDFLAGS} $^ -o $@ 

%.o: %.c ${HDRS}
	${CC} ${CFLAGS} -c $< -o $@

# by default targets are expected to be files /directories. the .PHONY statement change that.
# clean is very common target by convension, and is expected to clean any files generated by the 
# makefile (but not others!). Run by "make clean".
.PHONY: clean
clean:
	rm -f ${OBJS}

# Additional very common target to issue a "sanity" test
test: ${TARGET}
	./${TARGET} try.txt
